### ISSUE TITLE
Any plans to allow for booting multiple vm's and moving between them?

### ISSUE THREAD

**Issue by lonnietc** [phip1611/hedron-minimal-roottask#4]
Hello,

I like the Hedron (NOVA) kernel a lot and would like to learn how to extend your roottask more.

Are there any plans to extend the root task so that you will have some type of way to create/start/stop/destroy some simple VM's to allow paging between them like in the NOVA Demo 0.3

I am waning to  build up from an old Demo ISO's (https://os.inf.tu-dresden.de/nul/) to run their Demo 3, 17 February 2011 NUL 0.3 pre-released:

https://os.inf.tu-dresden.de/nul/NOVA-0.3.iso.bz2

This old demo basically allows to start multiple VM's and go through them with various key <F1> - <F12> and also start and stop little example VM's.  When you use the keys to switch through the VM's then it also switches the console to the active VM while the others are running in the background.

I am wondering if something like this might be possible as it would provide a good starting point.

On that note, I did come across the Redox Rust OS project (https://github.com/redox-os/redox) for which they have the relibc library that might be useful to extend your roottask as a thought.

**Comment by phip1611** [comment]
> Are there any plans to extend the root task so that you will have some type of way to create/start/stop/destroy some simple VM's to allow paging between them like in the NOVA Demo 0.3

I'd love to do that because I would learn so much. However, I have no resources left for that for the next months unfortunately.

**Comment by lonnietc** [comment]
I will keep investigating more on various NOVA hypervisor kernels since there are a number of them out there:

1. Genode OPS -- Patches one from Alex B. version (dated and Genode patched)
2.  Cyberus Hedron version
3. Udo Steinberg version
4. Maybe a few other laying about as well

Of these, I tend to think that Genode has a lot of development going on but I really do not like the way that their library is laid out and works.  It seems to make things very hard to work with and has too many interconnected libraries and patches to be of an real use to the average developer but is great if you are a Genode specialist.

The Hedron (NOVA) version may be also good as I understand that they have made a number of improvements over the core NOVA base but am not really clear as to what those specifically are compared to others.

Udo has what is probably the most recent updates but he tends to focus toward ARM development.

Anyway, maybe when you have more time we can look into things more and just let me know when you are available, ok.
Thanks Again
