### ISSUE TITLE
Seems to freeze on run

### ISSUE THREAD

**Issue by lonnietc** [phip1611/hedron-minimal-roottask#5]
Hello,

I have tested the latest build on Ubuntu 20.04 as well as Windows 10 with QEMU and it seems to freeze at the same point on both machines.

```
qemu-system-x86_64 -nodefaults -vga std -machine q35 -m 2048M -smp 2 -cpu IvyBridge -kernel hypervisor.elf32 -initrd hmr_stripped -serial stdio -monitor vc:1024x768

qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.f16c [bit 29]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.avx [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.f16c [bit 29]

Hello World from Roottask: hip_ptr=a[
```

You will notice that I also had to change the "-machine" setting as it would not work with your base settings

from:   -machine q35,accel=kvm:tcg

to:   -machine q35

**Comment by phip1611** [comment]
What happens with  `-machine q35,accel=kvm:tcg`? I think this project never runs without kvm, because several CPU features are required by Hedron already that the tiny code generator (TCG) of QEMU doesn't support/provide.

What CPU are you running? Ivy Bridge? Broadwell? Sky Lake?

**Comment by lonnietc** [comment]
Hello,

I am using one node of my "Dell PowerEdge C6220 SFF 4 Node Server 8x Xeon E5-2650 256GB RAM 4x 2TB 2.5" HD"

the output is:

![Screenshot from 2022-02-07 07-18-25](https://user-images.githubusercontent.com/15264930/152787012-33624f4a-21fa-41a4-af7d-27a46de7e402.png)

![Screenshot from 2022-02-07 07-17-44](https://user-images.githubusercontent.com/15264930/152787014-b3d267f2-14ce-4588-9a11-f604a67d245e.png)

**Comment by phip1611** [comment]
@lonnietc

Ahh you are running an Intel 2xxx generation CPU, i.e. sandybridge.

I can't reproduce this because my CPU is newer. I thought that QEMU automatically emulates newer CPU features, because host is specified as "IvyBridge" in QEMU's arguments.


Can you try this?
```
qemu-system-x86_64  -nodefaults -vga std -machine q35,accel=kvm:tcg -m 2048M -smp 2 -cpu "IvyBridge,+fsgsbase" -kernel hedron/build/src/hypervisor.elf32 -initrd roottask/target/x86_64-unknown-hedron/release/hmr_stripped roottask -serial stdio -monitor vc:1024x768
```

This is from my `./run_qemu.sh` script but with `-cpu "IvyBridge,+fsgsbase"`. Does this change anything for you? You can also try to use `-cpu "IvyBridge,+fsgsbase,+xsave"`

**Comment by lonnietc** [comment]
Nop, sorry but the same result in both cases that I tested:

-cpu "IvyBridge,+fsgsbase"

-cpu "IvyBridge,+fsgsbase,+xsave"

Perhaps Hedron is really only for newer CPU's and may not be viable to older legacy systems.

**Comment by lonnietc** [comment]
Also, you mentioned on your Github site "The roottask is not compatible with [NOVA](https://github.com/udosteinberg/NOVA), because it uses a Hedron-specific syscall. However, the build process would be the same."

Is this because the syscall has changed or that Hedron as added some capabilities that the Udo NOVA version does not support?

**Comment by phip1611** [comment]
@lonnietc

> Perhaps Hedron is really only for newer CPU's and may not be viable to older legacy systems.

See <https://github.com/cyberus-technology/hedron/blob/master/README.md>: 

> The Hedron microhypervisor runs on single- and multi-processor x86 machines that support ACPI, XSAVE and FSGSBASE.
> Recommended Intel CPUs are Intel Core processors starting with the Ivy Bridge microarchitecture. The virtualization features > are available on Intel CPUs with VMX and nested paging (EPT).

I don't know why QEMU can't handle this. I thought it is capable to emulate CPU features on older hardware. If you get it run, feel free to post a solution here. 

> The Hedron microhypervisor runs on single- and multi-processor x86 machines that support ACPI, XSAVE and FSGSBASE.
> Recommended Intel CPUs are Intel Core processors starting with the Ivy Bridge microarchitecture.

> Is this because the syscall has changed or that Hedron as added some capabilities that the Udo NOVA version does not support?

Hedron has a `pd_ctrl_delegate`-syscall that NOVA doesn't have. https://github.com/cyberus-technology/hedron/blob/master/doc/kernel-interface.md
This enables an easier approach to delegate capabilities compared to NOVA.

**Comment by lonnietc** [comment]
Thanks and that about clears it up for me.
