### ISSUE TITLE
Minimal Roottask for NOVA based upon this work

### ISSUE THREAD

**Issue by lonnietc** [phip1611/hedron-minimal-roottask#7]
Hello My Friend,

I have decided to take a step back into the NOVA world since although Hedron works for new systems, I find that NOVA w/NRE builds nicely for even older systems. Of course, it is lacking many of the wonderful advances that Hedron has incorporated and going forward I might have to work on adding some of them, but for now covering a larger scope of systems is a higher priority.

With that in mind, I was re-investigating your "Hedron-Minimal-Roottask" code which says "The roottask is not compatible with [NOVA](https://github.com/udosteinberg/NOVA), because it uses a Hedron-specific syscall. However, the build process for a NOVA roottask would be similar."

I would be interested to try and find out what changes might need to be made to make it work with NOVA since I like the idea of being able to call Rust libraries and code which could open up a lot of doors to push forward a NOVA branch.

Any thoughts that you might have on this would be greatly appreciated as I need to seek the installation of a C & Rust build library that will enable NOVE to build up some core applications.

Cheers and have a great day

**Comment by phip1611** [comment]
> I would be interested to try and find out what changes might need to be made to make it work with NOVA since I like the idea of being able to call Rust libraries and code which could open up a lot of doors to push forward a NOVA branch.

Nova doesn't has the PD_CTRL_DELEGATE system call used for right delegations. Instead, at least the old NOVA from 2010, uses a Portal call mechanism with an Echo Portal to delegate rights. I never used this mechanism and do not exactly know how it works out of the box.

For example, this will not work on Nova: https://github.com/phip1611/hedron-minimal-roottask/blob/main/roottask/src/serial.rs#L53
